name: A workflow for my Demo website
on: 
  workflow_dispatch:

jobs:
  build-job:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      name: Check out code
    - name: Echo Hello World
      run: echo Hello World
    - name: index.html content
      run: |
          echo "This is line1"
          echo "This is line2"
          cat index.html
          cat courses.html
