name: A workflow for my Demo website
on: push
jobs:
  build-job:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      name: Check out code
    - name: Check out code
      run: echo Hello World
    - name: index.html content
      run: cat index.html      
